### PR TITLE
Feature/tf module

### PR DESCRIPTION
**Pull request by cybershoguns**
Moves the config folder inside the terraform directory so you can easily access it when using the terraform module. Otherwise someone had to copy the user data script locally and in the same path.

Also adds the chosen server name to the beginning of the connect folder name. This helps keep different servers separate in case individual consultants or companies spin up multiple servers for Incident Response.

### CODE REVIEW

**Comment by IanCWeston** [comment]
That all sounds good :heavy_check_mark:

I see you're also copying the completed VR client.config.yaml file into the home directory and changing ownership accordingly.  What's the thought process there?

**Comment by cybershoguns** [comment]
@IanCWeston I'm almost done with it, but it's so that it makes it so we can get the file to the local machine in order to either distribute it to people or make it so a Jenkins Windows executor can create the MSIs. I'll add another commit here shortly that might help explain.

**Comment by IanCWeston** [comment]
@cybershoguns Makes sense now.  Are you done with this branch or do you have more commits to push?

**Comment by cybershoguns** [comment]
Nope feel free to close it. I have a couple other things I want to change/add, but I'll make separate branches/PRs for those to keep the scope of each one smaller and easier to digest.

**Comment by IanCWeston** [comment]
All approved.

**Pull request merged**
